# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db
      - /data/influxdb:/var/lib/influxdb
      - /mnt/FRITZ.NAS/NAS_DISK/Backup/influxdb:/backup
    ports:
      - "8086:8086"
      - "25826:25826/udp"

  collectd:
    image: knuppes/collectd-fritzbox:latest
    network_mode: host
    container_name: collectd-fritzbox
    environment:
      - TIMEZONE=Europe/Berlin
      - CheckInterval=10
      - InfluxDbIp=192.168.178.120
      - InfluxDbCollectdPort=25826
      - FritzBoxIp=192.168.178.1
      - FritzBoxUser=collectd
      - FritzBoxPassword=collectD
    depends_on:
      - influxdb
